name: MyGitVersionJob

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
      - 'release/**'
      - 'hotfix/**'

env:
  GITVERSION: 'gittools/gitversion:5.10.0-alpine.3.14-6.0'
  MAIN_BRANCHES: ("develop" "main")
  GITVERSION_TAG_PROPERTY_PULL_REQUESTS: .SemVer
  GITVERSION_TAG_PROPERTY_DEFAULT: .SemVer
  GITVERSION_TAG_PROPERTY_DEVELOP: .MajorMinorPatch,.PreReleaseLabelWithDash
  GITVERSION_TAG_PROPERTY_RELEASE: .MajorMinorPatch,.PreReleaseLabelWithDash
  GITVERSION_TAG_PROPERTY_HOTFIX: .MajorMinorPatch,.PreReleaseLabelWithDash
  GITVERSION_TAG_PROPERTY_MAIN: .MajorMinorPatch

jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debugging
        run: |
          # Print current working directory
          echo "Current working directory: $(pwd)"

          # Verify file accessibility
          versionFile="version.txt"
          if [ -f "$versionFile" ]; then
            echo "File '$versionFile' exists and is accessible."
          else
            echo "File '$versionFile' does not exist or is not accessible."
            exit 1
          fi

      - name: Fetch all history for all tags and branches
        run: git fetch --unshallow && git checkout develop && git checkout main

      # Continue with the rest of your steps as previously defined
      # ...

